### ISSUE TITLE
Test ASN.1 modules using a compiler

### ISSUE THREAD

**Issue by trishankkarthik** [uptane/asn1#1]
Test all the modules using an ASN.1 compiler!
- [x] CommonModule.asn1
- [x] MetadataModule.asn1
- [x] RootModule.asn1
- [x] TargetsModule.asn1
- [x] SnapshotModule.asn1
- [x] TimestampModule.asn1
- [x] TrustPinningModule.asn1
- [x] TimeServerModule.asn1
- [x] BootloaderModule.asn1
- [x] ApplicationModule.asn1

**Comment by samlauzon** [comment]
`sam@htpc:~/asn1c/asn1$ asn1c -Wdebug-lexer -Wdebug-compiler CommonModule.asn1 RootModule.asn1 SnapshotModule.asn1 TargetsModule.asn1 BootloaderModule.asn1 TimeServerModule.asn1 TimestampModule.asn1 TrustPinningModule.asn1`
 **_[ Output ]_** 
`FATAL: Module CommonModule referred in IMPORTS section for Version of module SnapshotModule does not contain the requested symbol in SnapshotModule.asn1

FATAL: Unknown type "Version" referenced by "version" at line 9 in SnapshotModule.asn1

FATAL: Module CommonModule referred in IMPORTS section for Version of module SnapshotModule does not contain the requested symbol in SnapshotModule.asn1

FATAL: ASN.1 expression "Roles" at line 62 of module TargetsModule
clashes with expression "Roles" at line 14 of module RootModule (RootModule.asn1).
Rename or remove either instance to resolve the conflict in TargetsModule.asn1

FATAL: Module CommonModule referred in IMPORTS section for Target of module BootloaderModule does not contain the requested symbol in BootloaderModule.asn1

FATAL: Unknown type "Target" referenced by "installedImage" at line 39 in BootloaderModule.asn1

FATAL: Module CommonModule referred in IMPORTS section for Target of module BootloaderModule does not contain the requested symbol in BootloaderModule.asn1

FATAL: ASN.1 expression "Signed" at line 16 of module TimeServerModule
clashes with expression "Signed" at line 31 of module BootloaderModule (BootloaderModule.asn1).
Rename or remove either instance to resolve the conflict in TimeServerModule.asn1

FATAL: Module CommonModule referred in IMPORTS section for Version of module TimestampModule does not contain the requested symbol in TimestampModule.asn1

FATAL: Unknown type "Version" referenced by "version" at line 9 in TimestampModule.asn1

FATAL: Module CommonModule referred in IMPORTS section for Version of module TimestampModule does not contain the requested symbol in TimestampModule.asn1

FATAL: ASN.1 expression "Delegations" at line 28 of module TrustPinningModule
clashes with expression "Delegations" at line 54 of module TargetsModule (TargetsModule.asn1).
Rename or remove either instance to resolve the conflict in TrustPinningModule.asn1`

 Looks like you can't use the same definition name twice? 
 (note: I've removed metadata and application... they are cross-reference breakage-to-the-max)

**Comment by trishankkarthik** [comment]
Thanks for the report, @samlauzon. Let me see what's going on. The first thing seems to be that more than one import statements is not allowed in ASN.1.

**Comment by trishankkarthik** [comment]
@samlauzon Should be fixed in f9774b0a301b06cea99344ecd4dab88c70c5826a. Try test-compile.sh.

Once you've verified that works, please close this issue?

**Comment by trishankkarthik** [comment]
@samlauzon reports:

> I ran your scripts but the -EF flag only runs the parser, doesn't create output.
> 
>  So I removed the flags and created the output.. it came out okay, I think..
> 
>  I renamed Makefile.am.sample to Makefile and attempted to build but it chokes on a struct definition in Metadata..
> 
> EncryptedSymmetricKey.h:23:14: error: nested redefinition of ‘enum keytype’
>  typedef enum keytype {
>               ^~~~~~~
> EncryptedSymmetricKey.h:23:14: error: redeclaration of ‘enum keytype’
> In file included from PublicKeys.h:40:0,
>                  from RootMetadata.h:14,
>                  from Signed.h:17,
>                  from Metadata.h:14,
>                  from Metadata.c:7:
> PublicKey.h:28:14: note: originally defined here
>  typedef enum keytype {
> 
>  ... 
>  Is it a redefinition because you're running the asn1c compiler multiple times. .. ?
>  does the second run manipulate the output from the first run?

**Comment by trishankkarthik** [comment]
Okay, I think I fixed the name clash in 63f888ec1cd906bad6d7f7fb866e4aeeb1e26fdf, but there's some compile error.
